PCbuilding/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("PCbuildingapp.urls")),
    path("", RedirectView.as_view(url="home/", permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + [path('accounts/', include('django.contrib.auth.urls')),
     path('tinymce/', include('tinymce.urls'))]

PCbuildingapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('forum/', views.get_postai, name='forum-main'),
    path('forum/threads/<str:cat>', views.get_postai_by_cat, name='forum'),
    path('pc-calculator/', views.get_all_setup_parts, name='bootleneck-calc'),
    path('forum/thread/<int:pk>', views.ThreadDetailView.as_view(), name='thread-one'),
    path('profilis/', views.profilis, name='profilis-url'),
    path('register/', views.register_user, name='register-url'),
    path('myposts/', views.UserPostaiListView.as_view(), name='my-postai'),
    path('myposts/new', views.PostasByUserCreateView.as_view(), name='my-postas-new'),
    path('myposts/update/<int:pk>', views.PostasByUserUpdateView.as_view(), name='my-postas-update'),
    path('advertisements/', views.get_advertisements, name='adverts'),
    path('advertisements/pc', views.get_advertisements_pc, name='adverts-pc'),
    path('advertisements/cpu', views.get_advertisements_cpu, name='adverts-cpu'),
    path('advertisements/gpu', views.get_advertisements_gpu, name='adverts-gpu'),
    path('advertisements/ram', views.get_advertisements_ram, name='adverts-ram'),
    path('myads/new', views.AdvertisementByUserCreateView.as_view(), name='my-ad-new'),
    path('advertisements/ext/<int:pk>', views.AdvertisementDetailView.as_view(), name='ad-one'),
]

PCbuildingapp/models.py
from django.db import models
from PIL import Image
from django.contrib.auth.models import User

# Create your models here.


class Cpu(models.Model):
    MANUFACTURER_LIST = (
        ('a', 'Amd'),
        ('i', 'Intel')
    )
    manufacturer = models.CharField(
        "Gamintojas",
        max_length=1,
        choices=MANUFACTURER_LIST,
        default='a'
    )
    model = models.CharField("Modelis", max_length=25)
    base_speed = models.CharField("Bazinis daznis", max_length=5)
    speed = models.CharField("Dažnis", max_length=5)
    cores = models.CharField("Branduolių kiekis", max_length=3)
    threads = models.CharField("Gijų kiekis", max_length=3)
    tdp = models.IntegerField("TDP")
    score = models.IntegerField('Skaičius palyginimui')

    def __str__(self):
        return f"{self.manufacturer} {self.model}"

    class Meta:
        verbose_name = 'Procesorius'
        verbose_name_plural = 'Procesoriai'


class Gpu(models.Model):
    MANUFACTURER_LIST = (
        ('a', 'Amd'),
        ('n', 'Nvidia'),
        ('i', 'Intel')
    )
    manufacturer = models.CharField(
        "Gamintojas",
        max_length=1,
        choices=MANUFACTURER_LIST,
        default='a'
    )
    model = models.CharField("Modelis", max_length=25)
    vram = models.CharField("Atminties kiekis", max_length=5)
    mem_type = models.CharField("Atminties tipas", max_length=7)
    POWER_OPTIONS = (
        ('n', 'Nereikalauja papildomo maitinimo'),
        ('6', '6 pinų'),
        ('8', '8 pinų'),
        ('6+6', '2 x 6 pinų'),
        ('8+6', '8 pinų + 6 pinų'),
        ('8+8', '2 x 8 pinų'),
        ('12', '12 pinų')
    )
    power_pins = models.CharField(
        "Reikalaujamas connectorius",
        max_length=3,
        choices=POWER_OPTIONS,
        default='n')
    tdp = models.IntegerField("TDP")
    score = models.IntegerField('Skaičius palyginimui')

    def __str__(self):
        return f"{self.model} {self.vram} GB"

    class Meta:
        verbose_name = 'Vaizdo plokštė'
        verbose_name_plural = 'Vaizdo plokštės'

class Ram(models.Model):
    MANUFACTURER_LIST = (
        ('k', 'Kingston'),
        ('cor', 'Corsair'),
        ('cru', 'Crucial'),
        ('a', 'Adata'),
        ('amd', 'AMD'),
        ('h', 'SK Hynix'),
        ('m', 'Micron'),
        ('s', 'Samsung'),
        ('p', 'Patriot')
    )

    manufacturer = models.CharField(
        "Gamintojas",
        max_length=3,
        choices=MANUFACTURER_LIST,
        default='k'
    )

    model = models.CharField("Modelis", max_length=25)
    TYPE_LIST = (
        ('2', 'DDR2'),
        ('3', 'DDR3'),
        ('4', 'DDR4'),
        ('5', 'DDR5')
    )
    type_ram = models.CharField(
        "Atminties tipas",
        max_length=1,
        choices=TYPE_LIST,
        default='4'
    )
    speed = models.CharField("Atminties greitis", max_length=4)
    size = models.IntegerField("Atminties dydis", null=True)

    def __str__(self):
        return f"{self.size}GB {self.model} {self.speed}"

    class Meta:
        verbose_name = 'Ram atmintis'
        verbose_name_plural = 'Ram atmintys'


class Profile(models.Model):
    picture = models.ImageField(upload_to='profile_pics', default='default-user.png')
    f_name = models.CharField("Vardas", max_length=30, null=True, blank=True)
    l_name = models.CharField("Pavardė", max_length=30, null=True, blank=True)
    reg_data = models.DateField("Registracijos data", auto_now_add=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} profilis'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # numatytieji Model klasės veiksmai suvykdomi
        img = Image.open(self.picture.path)
        thumb_size = (200, 200)
        img.thumbnail(thumb_size)
        img.save(self.picture.path)

    class Meta:
        verbose_name = 'Profilis'
        verbose_name_plural = 'Profiliai'


class UserRig(models.Model):
    profilis = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True)
    procesorius = models.ForeignKey(Cpu, on_delete=models.CASCADE, blank=True)
    vaizdo_plokste = models.ForeignKey(Gpu, on_delete=models.CASCADE, blank=True)
    ram_kiekis = models.CharField("RAM  plokštelių kiekis", max_length=2, blank=True)
    ramai = models.ForeignKey(Ram, on_delete=models.CASCADE, blank=True)

    class Meta:
        verbose_name = 'Naudotojo kompiuteris'
        verbose_name_plural = 'Naudotojų kompiuteriai'


class Postai(models.Model):
    CATEGORY_LIST = (
        ('s', 'Pagalba surinkime nuo nulio'),
        ('a', 'Atnaujinimas seno kompiuterio'),
        ('p', 'Problemos su kompiuteriu'),
        ('k', 'Kiti įrenginiai'),
        ('r', 'Tematiški renginiai')
    )
    category = models.CharField(
        "Kategorija",
        max_length=1,
        choices=CATEGORY_LIST,
        default='s'
    )

    STATUS_LIST = (
        ('a', 'Aktyvi'),
        ('u', 'Uždaryta'),
        ('p', 'Paslėpta'),
        ('d', 'Ištrinta'),
        ('v', 'VIP')
    )

    status = models.CharField(
        "Statusas",
        max_length=1,
        choices=STATUS_LIST,
        default='a',
        blank=True,
        null=True
    )
    theme = models.CharField("Tema", max_length=150)
    description = models.CharField("Aprašymas", max_length=5000)
    ft_1 = models.ImageField("Paveiksliukas Nr. 1", upload_to='post_pics', default='no_photo.jpg')
    ft_2 = models.ImageField("Paveiksliukas Nr. 2", upload_to='post_pics', default='no_photo.jpg')
    ft_3 = models.ImageField("Paveiksliukas Nr. 3", upload_to='post_pics', default='no_photo.jpg')
    ft_4 = models.ImageField("Paveiksliukas Nr. 4", upload_to='post_pics', default='no_photo.jpg')
    ft_5 = models.ImageField("Paveiksliukas Nr. 5", upload_to='post_pics', default='no_photo.jpg')
    create_data = models.DateTimeField("Sukurimo data", auto_now_add=True, null=True, blank=True)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # numatytieji Model klasės veiksmai suvykdomi
        img = Image.open(self.ft_1.path)
        img.save(self.ft_1.path)
        img = Image.open(self.ft_2.path)
        img.save(self.ft_2.path)
        img = Image.open(self.ft_3.path)
        img.save(self.ft_3.path)
        img = Image.open(self.ft_4.path)
        img.save(self.ft_4.path)
        img = Image.open(self.ft_5.path)
        img.save(self.ft_5.path)


    class Meta:
        verbose_name = 'Postas'
        verbose_name_plural = 'Postai'

class PostaiReview(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Komentaras postui', max_length=2000)
    postas = models.ForeignKey(Postai, on_delete=models.CASCADE, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    ft = models.ImageField('Komentaro paveiksliukas', upload_to='review_pics', default='no_photo.jpg')

    def __str__(self):
        return f"{self.date_created}, {self.reviewer}, {self.postas}, {self.content[:50]}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # numatytieji Model klasės veiksmai suvykdomi
        img = Image.open(self.ft.path)
        img.save(self.ft.path)

    class Meta:
        verbose_name = 'Posto komentaras'
        verbose_name_plural = 'Posto komentarai'

class Advertisements(models.Model):
    kaina = models.FloatField(blank=True, null=True)
    telefonas = models.CharField(blank=True, default='+370', max_length=13)
    tema = models.CharField(blank=True, null=True, max_length=150)
    aprasymas = models.CharField('Aprašymas', blank=True, null=True, max_length=2500)
    cpu_kiekis = models.IntegerField(blank=True, default=0, null=True)
    cpu_modelis = models.ForeignKey(Cpu, on_delete=models.CASCADE, blank=True, null=True)
    gpu_kiekis = models.IntegerField(blank=True, default=0, null=True)
    gpu_modelis = models.ForeignKey(Gpu, on_delete=models.CASCADE, blank=True, null=True)
    ram_kiekis = models.IntegerField(blank=True, default=0, null=True)
    ram_modelis = models.ForeignKey(Ram, on_delete=models.CASCADE, blank=True, null=True)
    useris = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    STATUS_LIST = (
        ('a', 'Aktyvus'),
        ('p', 'Paslėptas'),
        ('d', 'Ištrintas'),
        ('v', 'VIP')
    )

    status = models.CharField(
        "Statusas",
        max_length=1,
        choices=STATUS_LIST,
        default='a',
        blank=True,
        null=True
    )

    ft_1 = models.ImageField("Paveiksliukas Nr. 1", upload_to='advertisement_pics', default='no_photo.jpg')
    ft_2 = models.ImageField("Paveiksliukas Nr. 2", upload_to='advertisement_pics', default='no_photo.jpg')
    ft_3 = models.ImageField("Paveiksliukas Nr. 3", upload_to='advertisement_pics', default='no_photo.jpg')
    ft_4 = models.ImageField("Paveiksliukas Nr. 4", upload_to='advertisement_pics', default='no_photo.jpg')



    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # numatytieji Model klasės veiksmai suvykdomi
        img = Image.open(self.ft_1.path)
        img.save(self.ft_1.path)
        img = Image.open(self.ft_2.path)
        img.save(self.ft_2.path)
        img = Image.open(self.ft_3.path)
        img.save(self.ft_3.path)
        img = Image.open(self.ft_4.path)
        img.save(self.ft_4.path)

    class Meta:
        verbose_name = 'Skelbimas'
        verbose_name_plural = 'Skelbimai'

class AdvertisementReview(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Komentaras skelbimui', max_length=2000)
    advert = models.ForeignKey(Advertisements, on_delete=models.CASCADE, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):

PCbuildingapp/forms.py
from django import forms

from .models import Profile, User, Postai, PostaiReview, Advertisements, AdvertisementReview


class PostasReviewForm(forms.ModelForm):
    class Meta:
        model = PostaiReview
        fields = ('content', 'postas', 'reviewer', 'ft')
        widgets = {
            'postas': forms.HiddenInput(),
            'reviewer': forms.HiddenInput()
        }


class AdvertisementReviewForm(forms.ModelForm):
    class Meta:
        model = AdvertisementReview
        fields = ('content', 'advert', 'reviewer')
        widgets = {
            'advert': forms.HiddenInput(),
            'reviewer': forms.HiddenInput()
        }


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('f_name', 'l_name', 'picture')


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)


class DateInput(forms.DateInput):
    input_type = 'date'


class UserPostasCreateForm(forms.ModelForm):
    class Meta:
        model = Postai
        fields = ('category', 'theme', 'status',
                  'description', 'ft_1', 'ft_2', 'ft_3', 'ft_4', 'ft_5', 'creator')
        widgets = {
            'creator': forms.HiddenInput(),
            'status': forms.HiddenInput(),
        }


class UserAdvertisementCreateForm(forms.ModelForm):
    class Meta:
        model = Advertisements
        fields = ('kaina', 'telefonas', 'tema', 'aprasymas',
                  'cpu_kiekis', 'cpu_modelis', 'gpu_kiekis', 'gpu_modelis', 'ram_kiekis', 'ram_modelis',
                  'ft_1', 'ft_2', 'ft_3', 'ft_4', 'status', 'useris')
        widgets = {
            'useris': forms.HiddenInput(),
            'status': forms.HiddenInput(),
        }

PCbuildingapp/templates/advertisement.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="grid-container-ad-single">
    <div style="grid-column: span 6;">
    <h2 style="text-align: center;">{{ ad.tema }}</h2>
    </div>
    {% if ad.ft_1 and ad.ft_1.url != '/media/no_photo.jpg' %}
    <div style="grid-column: span 6; text-align: center;">
    <img class="ad_pav" id="pagr_skelbimo_pav" src="{{ ad.ft_1.url }}"/>
    </div>
    {% endif %}
    {% if ad.ft_2 and ad.ft_2.url != '/media/no_photo.jpg' and ad.ft_3 and ad.ft_3.url != '/media/no_photo.jpg' and ad.ft_4 and ad.ft_4.url != '/media/no_photo.jpg' %}
    <div style="grid-column: span 2; text-align: right;" onclick="document.getElementById('pagr_skelbimo_pav').src='{{ ad.ft_1.url }}'">
    <img class="ad_thumb_pav" src="{{ ad.ft_1.url }}"/>
    </div>
    <div style="text-align: center;" onclick="document.getElementById('pagr_skelbimo_pav').src='{{ ad.ft_2.url }}'">
    <img class="ad_thumb_pav" src="{{ ad.ft_2.url }}"/>
    </div>
    <div style="text-align: center;" onclick="document.getElementById('pagr_skelbimo_pav').src='{{ ad.ft_3.url }}'">
    <img class="ad_thumb_pav" src="{{ ad.ft_3.url }}"/>
    </div>
    <div style="grid-column: span 2; text-align: left;" onclick="document.getElementById('pagr_skelbimo_pav').src='{{ ad.ft_4.url }}'">
    <img class="ad_thumb_pav" src="{{ ad.ft_4.url }}"/>
    </div>
    {% elif ad.ft_2 and ad.ft_2.url != '/media/no_photo.jpg' and ad.ft_3 and ad.ft_3.url != '/media/no_photo.jpg' %}
    <div style="grid-column: span 2; text-align: right;" onclick="document.getElementById('pagr_skelbimo_pav').src='{{ ad.ft_1.url }}'">
    <img class="ad_thumb_pav" src="{{ ad.ft_1.url }}"/>
    </div>
    <div style="grid-column: span 2; text-align: center;" onclick="document.getElementById('pagr_skelbimo_pav').src='{{ ad.ft_2.url }}'">
    <img class="ad_thumb_pav" src="{{ ad.ft_2.url }}"/>
    </div>
    <div style="grid-column: span 2; text-align: left;" onclick="document.getElementById('pagr_skelbimo_pav').src='{{ ad.ft_3.url }}'">
    <img class="ad_thumb_pav" src="{{ ad.ft_3.url }}"/>
    </div>
    {% elif ad.ft_2 and ad.ft_2.url != '/media/no_photo.jpg' %}
    <div style="grid-column: span 3; text-align: right;" onclick="document.getElementById('pagr_skelbimo_pav').src='{{ ad.ft_1.url }}'">
    <img class="ad_thumb_pav" src="{{ ad.ft_1.url }}"/>
    </div>
    <div style="grid-column: span 3;" onclick="document.getElementById('pagr_skelbimo_pav').src='{{ ad.ft_2.url }}'">
    <img class="ad_thumb_pav" src="{{ ad.ft_2.url }}"/>
    </div>
    {% endif %}
    <div></div>
<div style="grid-column: span 5;">
    <h4 style="padding: 5px; color: white;">Specifikacijos:</h4>
</div>
    {% if ad.cpu_kiekis > 0 %}
    <div></div>
    <div style="grid-column: span 5;">
        Procesorius: {{ ad.cpu_modelis.get_manufacturer_display }} {{ ad.cpu_modelis.model }}
    </div>
    {% endif %}
    {% if ad.gpu_kiekis > 0 %}
    <div></div>
    <div style="grid-column: span 5;">
        Vaizdo plokštė: {{ ad.gpu_modelis.get_manufacturer_display }} {{ ad.gpu_modelis.model }}
    </div>
    {% endif %}
    {% if ad.ram_kiekis > 0 %}
    <div></div>
    <div style="grid-column: span 5;">
        Ram kiekis: {{ ad.ram_kiekis }}
    </div>
    <div></div>
    <div style="grid-column: span 5;">
        Ram: {{ ad.ram_modelis.get_manufacturer_display }} {{ ad.ram_modelis.model }} {{ ad.ram_modelis.size }} {{ ad.ram_modelis.speed }} MHz
    </div>
    {% endif %}
    {% if ad.aprasymas %}
    <div></div>
    <div style="grid-column: span 5;">
    <h4 style="padding: 5px; color: white;">Aprašymas:</h4>
    </div>
    <div style="grid-column: span 6;">
        <small>{{ ad.aprasymas }}</small>
    </div>
    {% endif %}
    <div></div>
    <div style="grid-column: span 5;">
    <h4 style="padding: 5px; color: white;">Savininko kontaktai:</h4>
    </div>
    <div></div>
    <div style="grid-column: span 5;">
        Telefonas: {{ ad.telefonas }}
    </div>
    <div></div>
    <div style="grid-column: span 5;">
        El paštas: {{ ad.useris.email }}
    </div>

</div>
<br>
<br>
<br>
<br>
{% endblock %}

PCbuildingapp/templates/bootleneck_calc.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
<div class="container">
<h2>Pasirinkite komponentus:</h2>
    <form action="/action_page.php">
    <div class="form-group">
    <label>Pasirinkite procesorių:</label>
    <select class="form-control" id="cpu-select" name="cpu-select-list">
        {% for cpu in cpus %}
        <option>{{ cpu.get_manufacturer_display }} {{ cpu.model }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
    <label>Pasirinkite vaizdo plokštę:</label>
    <select class="form-control" id="gpu-select" name="gpu-select-list">
        {% for gpu in gpus %}
        <option>{{ gpu.get_manufacturer_display }} {{ gpu.model }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
    <label>Pasirinkite ram plokštelių kiekį:</label>
    <select class="form-control" id="ram-count-select" name="ram-count-select-list">
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
        <option>6</option>
        <option>7</option>
        <option>8</option>
      </select>
    </div>
    <div class="form-group">
    <label>Pasirinkite ram:</label>
    <select class="form-control" id="ram-select" name="ram-select-list">
        {% for ram in rams %}
        <option>{{ ram.get_manufacturer_display }} {{ ram.model }} {{ ram.size }}GB {{ ram.speed }}MHz {{ ram.get_type_ram_display }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
    <label>Pasirinkite rezoliuciją:</label>
    <select class="form-control" id="res-select" name="res-select-list">
        <option>Full HD (1920x1080)</option>
        <option>2K (2560x1440 arba 2560x1600)</option>
        <option>4K (3840x2160)</option>
      </select>
    </div>
    <div class="form-group">
    <label>Pasirinkite pagrindines užduotys (žaidimams palikite tuščią):</label>
    <select class="form-control" id="main-task-select" name="main-task-select-list">
        <option>---</option>
        <option>CPU intense tasks</option>
        <option>GPU intense task</option>
      </select>
    </div>
        <button type="submit" class="btn btn-primary">Paskaičiuoti kompiuterio balansą</button>
    </form>
</div>
<br>
<br>
<br>
<br>
{% endblock %}

PCbuildingapp/templates/forum_themes.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    {% for kat in kategorijos %}
        <div class="forum" style="margin-top: 10px;">
            <h2>{{ kat }} <a href="#"><i>Peržiūrėti kitus temos postus>></i></a></h2>
            <div class="thread">
                <h3><a href="#">Welcome to the Dark Forum</a></h3>
                <p>Started by Admin on May 28, 2024</p>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

PCbuildingapp/templates/my_posts.html
{% extends "base.html" %}
{% block content %}

<h2>Mano postai:</h2>
{% if postai %}
    {% for postas in postai %}
        <hr>
        <h4>Kategorija: {{ postas.get_category_display }}</h4>
        <h4>Statusas: {{ postas.get_status_display }}</h4>
        <div class="forumas">
            <h4><a href="{% url 'thread-one' postas.id %}"
            style="color:{% if postas.status == 'v' %}
            yellow
            {% elif postas.status == 'a' %}
            lime
            {% else %}
            gray
            {% endif %}">
                {% if postas.status == 'v' %}<span style="font-size:120%;color:yellow;">&starf;</span>{% endif %}
                {{ postas.theme }}
                {% if postas.status == 'v' %}<span style="font-size:120%;color:yellow;">&starf;</span>{% endif %}
            </a></h4>
            <div class="threadas">
                <small>Pradėta: {{ postas.creator }}</small><br>
                <small>{{ postas.create_data }}</small>
            </div>
        </div>
        <br>
        <button onclick="">Paslėpti/Atslėpti</button>
    {% endfor %}
    {% else %}
    <div class="forum">
            <h4>Dėja kolkas nėra postų... :(</h4>
        <div class="thread">
        Gal būsi pirmas, kas parašys?
        </div>
    </div>
    {% endif %}
<br>
<br>
<br>
<br>

{% endblock %}

PCbuildingapp/templates/psu_calc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

PCbuildingapp/templates/thread.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

{% if user.is_authenticated and user == post.creator %}
<div class="topnav">
    <a href="{% url 'my-postas-update' post.id %}">Redaguoti postą!</a>
</div><br>
{% endif %}

<div class="grid-container">
  <div class="item1">{{ post.theme }} <small style="color:#7a7977;"><i>{{ post.create_data }}</i></small></div>
  <div class="item2">Kurėjas: <br><small><i>{{ post.creator }}</i></small><br>
  </div>

    <div class="item3"><p style="font-size: 16px">{{ post.description }}</p>

    {% if post.ft_1 and post.ft_1.url != '/media/no_photo.jpg' %}
      <br>
      <p style="font-size: 14px"><i>Prikabintas paveiksliukas:</i><p>
      <img class="posto_pav" src="{{ post.ft_1.url }}"/>
    {% endif %}
    {% if post.ft_2 and post.ft_2.url != '/media/no_photo.jpg' %}
      <br>
      <p style="font-size: 14px"><i>Prikabintas paveiksliukas:</i><p>
    <img class="posto_pav" src="{{ post.ft_2.url }}"/>
    {% endif %}
    {% if post.ft_3 and post.ft_3.url != '/media/no_photo.jpg' %}
        <br>
      <p style="font-size: 14px"><i>Prikabintas paveiksliukas:</i><p>
    <img class="posto_pav" src="{{ post.ft_3.url }}"/>
    {% endif %}
    {% if post.ft_4 and post.ft_4.url != '/media/no_photo.jpg' %}
        <br>
      <p style="font-size: 14px"><i>Prikabintas paveiksliukas:</i><p>
    <img class="posto_pav" src="{{ post.ft_4.url }}"/>
    {% endif %}
    {% if post.ft_5 and post.ft_5.url != '/media/no_photo.jpg' %}
        <br>
      <p style="font-size: 14px"><i>Prikabintas paveiksliukas:</i><p>
    <img class="posto_pav" src="{{ post.ft_5.url }}"/>
    {% endif %}
  </div>
</div>
<br>
<h1>Atsakymai:</h1><hr/>
{% if post.postaireview_set.all %}
    {% for komentaras in post.postaireview_set.all %}
        <div class="grid-container-ats">

        <div>Kurėjas: <br><small><i>{{ komentaras.reviewer }}</i></small><br>
        <small style="font-size: 14px"><i>{{ komentaras.date_created }}</i></small><br>
        </div>
            <div>
                <p style="font-size: 16px">

                    {{ komentaras.content }}</p>
                    {% if komentaras.ft and komentaras.ft.url != '/media/no_photo.jpg' %}
                        <br>
                        <p style="font-size: 14px"><i>Prikabintas paveiksliukas:</i><p>
                        <img class="posto_pav" src="{{ komentaras.ft.url }}"/>
                    {% endif %}
            </div>
        </div>
<hr/>
    {% endfor %}
{% else %}
    <p>Postas  kolkas neturi atsakymų...</p>
{% endif %}

{% if user.is_authenticated %}
<div>
    <h5>Palikite komentarą postui</h5>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <div>
        <input type="submit" class="btn btn-outline-success btn-sm" value="Išsaugoti komentarą"/>
        </div>
    </form>
</div>
{% endif %}
<br>
<br>
<br>
<br>
{% endblock %}